
import { GameDefinition, GameType, Language } from '../types';

export const getGames = (lang: Language): GameDefinition[] => {
  return [
  {
    id: GameType.SECRET_CODE,
    title: { en: "Secret Code", zh: "秘密代号" },
    description: { en: "Team word association game.", zh: "团队词语联想游戏。" },
    icon: "🕵️‍♂️",
    color: "from-slate-700 to-slate-900",
    minPlayers: 4,
    rules: { en: "1. Divide into Red & Blue teams.\n2. Spymasters see card colors.\n3. Spymaster gives 1 word clue.\n4. Team guesses their words.\n5. Avoid the Assassin!", zh: "1. 分为红蓝两队。\n2. 间谍头目可以看到卡片颜色。\n3. 头目给出一个词的线索。\n4. 队员猜词。\n5. 小心刺客！" }
  },
  {
    id: GameType.TRIVIA,
    title: { en: "AI Trivia", zh: "AI 趣味问答" },
    description: { en: "Infinite questions on any topic.", zh: "任意主题的无限问答。" },
    icon: "🧠",
    color: "from-blue-600 to-indigo-600",
    minPlayers: 1,
    rules: { en: "1. Choose topic.\n2. Answer correctly for 10pts.", zh: "1. 选择主题。\n2. 答对得10分。" }
  },
  {
    id: GameType.WHO_AM_I,
    title: { en: "Who Am I?", zh: "我是谁？" },
    description: { en: "Forehead guessing game.", zh: "额头猜词游戏。" },
    icon: "🤔",
    color: "from-yellow-500 to-amber-600",
    minPlayers: 2,
    rules: { en: "1. Place phone on forehead.\n2. Friends give clues.\n3. Tilt/Tap to pass or correct.", zh: "1. 将手机放在额头。\n2. 朋友给线索。\n3. 点击跳过或正确。" }
  },
  {
    id: GameType.CHARADES,
    title: { en: "Mime Time", zh: "你划我猜" },
    description: { en: "Act out AI scenarios.", zh: "表演AI生成的场景。" },
    icon: "🎭",
    color: "from-purple-600 to-fuchsia-600",
    minPlayers: 2,
    rules: { en: "1. Actor acts without words.\n2. Guess within time limit.", zh: "1. 表演者无声表演。\n2. 限时猜出词语。" }
  },
  {
    id: GameType.PICTIONARY,
    title: { en: "Quick Draw", zh: "灵魂画手" },
    description: { en: "Draw words generated by AI.", zh: "根据AI生成的词语绘画。" },
    icon: "🎨",
    color: "from-pink-500 to-rose-600",
    minPlayers: 2,
    rules: { en: "1. Artist draws the word.\n2. Team guesses.\n3. Paper & Pen required!", zh: "1. 画家画出词语。\n2. 团队猜测。\n3. 需要纸和笔！" }
  },
  {
    id: GameType.SCATTERGORIES,
    title: { en: "Category Rush", zh: "分类冲刺" },
    description: { en: "Name things starting with a letter.", zh: "列举指定字母开头的物品。" },
    icon: "📝",
    color: "from-orange-500 to-red-500",
    minPlayers: 2,
    rules: { en: "1. Get Letter & Categories.\n2. Write words for each.\n3. Must start with Letter.", zh: "1. 获取字母和分类。\n2. 写出对应词语。\n3. 必须以该字母开头。" }
  },
  {
    id: GameType.FORBIDDEN_WORDS,
    title: { en: "Forbidden Words", zh: "禁忌词" },
    description: { en: "Describe without saying forbidden words.", zh: "描述词语，但不能说出禁忌词。" },
    icon: "🤐",
    color: "from-violet-600 to-purple-800",
    minPlayers: 2,
    rules: { en: "1. Describe the Target Word.\n2. DO NOT use the Forbidden Words.\n3. Team guesses to score.", zh: "1. 描述目标词。\n2. 禁止使用禁忌词。\n3. 队友猜对得分。" }
  },
  {
    id: GameType.DEBATE,
    title: { en: "Debate Duel", zh: "奇葩辩论" },
    description: { en: "Argue absurd topics.", zh: "为荒谬的话题辩论。" },
    icon: "🗣️",
    color: "from-red-600 to-orange-700",
    minPlayers: 2,
    rules: { en: "1. Get assigned a stance.\n2. Argue your case.\n3. Audience votes.", zh: "1. 获取立场。\n2. 陈述观点。\n3. 观众投票。" }
  },
  {
    id: GameType.IMPOSTOR,
    title: { en: "Impostor", zh: "谁是卧底" },
    description: { en: "Find the spy.", zh: "找出隐藏的卧底。" },
    icon: "🕵️",
    color: "from-emerald-600 to-teal-700",
    minPlayers: 3,
    rules: { en: "1. Impostor doesn't know location.\n2. Ask questions to find them.", zh: "1. 卧底不知道地点。\n2. 提问找出卧底。" }
  },
  {
    id: GameType.MURDER_MYSTERY,
    title: { en: "Murder Mystery", zh: "剧本杀" },
    description: { en: "Solve the crime.", zh: "破解谋杀谜案。" },
    icon: "🩸",
    color: "from-red-800 to-rose-950",
    minPlayers: 4,
    rules: { en: "1. Read secret roles.\n2. Detective interrogates.\n3. Find the killer.", zh: "1. 阅读秘密角色。\n2. 侦探审问。\n3. 找出凶手。" }
  },
  {
    id: GameType.WOULD_YOU_RATHER,
    title: { en: "Would You Rather", zh: "你宁愿" },
    description: { en: "Tough choices generated by AI.", zh: "AI生成的艰难选择。" },
    icon: "⚖️",
    color: "from-cyan-500 to-blue-600",
    minPlayers: 2,
    rules: { en: "1. Read the two options.\n2. Everyone votes on what they'd rather do.\n3. Discuss your choices!", zh: "1. 阅读两个选项。\n2. 每个人投票选择自己宁愿做的事。\n3. 讨论你们的选择！" }
  },
  {
    id: GameType.TWO_TRUTHS,
    title: { en: "Two Truths & A Lie", zh: "两真一假" },
    description: { en: "Spot the AI's lie, or submit your own.", zh: "找出AI的谎言，或提交你自己的。" },
    icon: "🤥",
    color: "from-lime-500 to-green-600",
    minPlayers: 2,
    rules: { en: "1. Read the 3 statements.\n2. 2 are true, 1 is a lie.\n3. Vote on which one is the lie.", zh: "1. 阅读3个陈述。\n2. 2个是真的，1个是假的。\n3. 投票选出哪个是谎言。" }
  },
  {
    id: GameType.NEVER_HAVE_I_EVER,
    title: { en: "Never Have I Ever", zh: "我从来没有" },
    description: { en: "Discover secrets about your friends.", zh: "发现朋友们的秘密。" },
    icon: "🫣",
    color: "from-fuchsia-500 to-pink-600",
    minPlayers: 2,
    rules: { en: "1. Read the statement.\n2. If you HAVE done it, lose a point (or take a sip).\n3. Last person standing wins.", zh: "1. 阅读陈述。\n2. 如果你做过，扣一分（或喝一口）。\n3. 坚持到最后的人获胜。" }
  }
  ];
};
